OPENAI_API_KEY = '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'
BASE_URL = "http://localhost:8501"
GOOGLE_DRIVE = "https://drive.google.com/uc?id="
PAGE_ICON = "https://drive.google.com/uc?id=1eNH6VVQ69_u_eRFZGRTyfM0iiWHW5P-y"